project_name: NengoDL
pkg_name: nengo_dl
repo_name: nengo/nengo-dl

description: Deep learning integration for Nengo
copyright_start: 2015

license_rst: {}

contributing_rst: {}

# contributors_rst: {}

manifest_in:
  prune:
    - docs/whitepaper
    - tmp
  global-exclude:
    - "*.bat"
    - "*.svg"

setup_cfg:
  pytest:
    addopts:
      - -p nengo.tests.options
      - --simulator nengo_dl.Simulator
      - --ref-simulator nengo_dl.Simulator
      - --disable-warnings
    filterwarnings:
      - always
    xfail_strict: True
    nengo_test_unsupported:
      nengo/tests/test_simulator.py:test_warn_on_opensim_del:
        nengo_dl raises a different (more visible) warning, see
        tests/test_nengo_tests.py:test_warn_on_opensim_del
      nengo/tests/test_simulator.py:test_signal_init_values:
        different method required to manually step simulator, see
        tests/test_nengo_tests.py:test_signal_init_values
      nengo/tests/test_simulator.py:test_entry_point:
        overridden so we can pass custom test simulators, see
        tests/test_nengo_tests.py:test_entry_point
      nengo/tests/test_simulator.py:test_simulator_progress_bars:
        nengo_dl uses a different progress bar system, see
        tests/test_utils.py:test_progress_bar
      nengo/tests/test_simulator.py:test_dtype[*:
        nengo_dl uses a different system for signals/dtype, see
        tests/test_nengo_tests.py:test_dtype
      nengo/tests/test_node.py:test_args:
        time is passed as np.float32, not a float, see
        tests/test_nengo_tests.py:test_args
      nengo/tests/test_node.py:test_unconnected_node:
        need to set `unroll_simulation` to ensure node runs the correct
        number of times, see
        tests/test_nengo_tests.py:test_unconnected_node
      nengo/tests/test_synapses.py:test_alpha:
        need to set looser tolerances due to float32 implementation, see
        tests/test_processes.py:test_alpha
      nengo/tests/test_synapses.py:test_linearfilter:
        need to set looser tolerances due to float32 implementation, see
        tests/test_processes.py:test_linearfilter
      nengo/tests/test_ensemble.py:test_gain_bias:
        use allclose instead of array_equal, see
        tests/test_simulator.py:test_gain_bias
      nengo/tests/test_transforms.py:test_convolution*:
        need to set looser tolerances due to float32 implementation, see
        tests/test_transforms.py:test_convolution
      nengo/tests/test_transforms.py:test_sparse[False-*:
        nengo-dl doesn't raise a warning for scipy=False, see
        tests/test_nengo_tests.py:test_sparse
      nengo/tests/test_copy.py:test_pickle_sim[*:
        nengo-dl does not support pickling a Simulator, see
        tests/test_simulator.py:test_pickle_error
  pylint:
    known_third_party:
      - PIL
      - progressbar
      - tensorflow
  coverage:
    omit_files:
      - nengo_dl/tests/dummies.py
  flake8:
    ignore:
      - C901

docs_conf_py:
  extensions:
    - sphinx_click.ext
  nengo_logo: nengo-dl-full-light.svg
  nengo_logo_color: "#ff6600"
  sphinx_options:
    suppress_warnings: "['image.nonlocal_uri']"
  analytics_id: UA-41658423-2

ci_scripts:
  - template: static
  - template: test
    pip_install:
      - $NUMPY_VERSION
      - $TF_VERSION
      - $NENGO_VERSION
      - $SCIPY_VERSION
      - git+https://github.com/drasmuss/spaun2.0.git
    nengo_tests: true
  - template: test
    output_name: test-coverage
    coverage: true
    pip_install:
      - --pre
      - $NUMPY_VERSION
      - $TF_VERSION
      - $NENGO_VERSION
      - $SCIPY_VERSION
      - git+https://github.com/drasmuss/spaun2.0.git
    nengo_tests: true
  - template: examples
    post_commands:
      - python docs/whitepaper/whitepaper2018_code.py > /dev/null
  - template: docs
  - template: deploy
  - template: gpu

travis_yml:
  python: 3.6
  global_vars:
    NUMPY_VERSION: numpy
    TF_VERSION: tensorflow
    NENGO_VERSION: nengo
    SCIPY_VERSION: noop
  jobs:
    - script: static
    - script: docs
    - cache: false
    - script: gpu
      test_args: --device /gpu:3 --performance
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git
        TF_VERSION: tensorflow-gpu
    - script: test-coverage
      env:
        NENGO_VERSION: git+https://github.com/nengo/nengo.git#egg=nengo
        TF_VERSION: tensorflow
        SCIPY_VERSION: scipy
      dist: xenial
      python: 3.7
    - script: test-coverage
      env:
        NENGO_VERSION: nengo==2.8.0
        TF_VERSION: tensorflow==1.4.0
        NUMPY_VERSION: numpy==1.14.5
      python: 3.5
    - test_args: --dtype float64 --simulator-only
    - test_args: --unroll-simulation 5 --simulator-only
    - test_args: --inference-only --simulator-only
    - script: examples
  pypi_user: drasmuss
  deploy_dists:
    - sdist

codecov_yml: {}

setup_py:
  include_package_data: True
  docs_req:
    - click>=6.7  # needed for sphinx-click
    - jupyter>=1.0.0
    - matplotlib>=2.0.0
    - nbsphinx>=0.3.5
    - nengo-sphinx-theme>=0.7.0
    - numpydoc>=0.6.0
    - Pillow>=4.1.1
    - sphinx>=1.8.0
    - sphinx-click>=1.4.1
  tests_req:
    - click>=6.7
    - codespell>=1.12.0
    - matplotlib>=2.0.0,<3.1.0  # >=3.1.0 doesn't work with nengo tests TODO: remove once there is a compatible nengo release
    - nbval>=0.6.0
    - pylint>=1.9.2
    - pytest>=3.6.0,<4.1.0  # >=4.1.0 doesn't work with nengo tests TODO: remove this once there is a compatible nengo release
    - pytest-cov>=2.6.0
    - pytest-xdist>=1.16.0,<1.28.0  # 1.28.0 requires pytest>=4.4.0 (see above)
    - six>=1.11.0  # hint for pip dependency resolution, required by nbval
  entry_points:
    nengo.backends:
      - dl = nengo_dl:Simulator
  classifiers:
      - "Development Status :: 5 - Production/Stable"
      - "Framework :: Nengo"
      - "Intended Audience :: Science/Research"
      - "License :: Free for non-commercial use"
      - "Operating System :: Microsoft :: Windows"
      - "Operating System :: POSIX :: Linux"
      - "Programming Language :: Python"
      - "Programming Language :: Python :: 3.5"
      - "Programming Language :: Python :: 3.6"
      - "Programming Language :: Python :: 3.7"
      - "Topic :: Scientific/Engineering"
      - "Topic :: Scientific/Engineering :: Artificial Intelligence"
